export enum QuestionType {
    TRAVEL_TASTE = "TRAVEL_TASTE",
    DIETARY_RESTRICTIONS = "DIETARY_RESTRICTIONS",
    TRIP_DURATION = "TRIP_DURATION",
    AIRPORT = "AIRPORT",
    START_DATE = "START_DATE",
    START_DATE_FLEXIBILITY = "START_DATE_FLEXIBILITY",
    BUDGET = "BUDGET",
    NUMBER_OF_TRAVELLERS = "NUMBER_OF_TRAVELLERS"
  }
  